dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter v0.142.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlpexporter v0.142.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.142.0

receivers:
  - gomod:
      go.opentelemetry.io/collector/receiver/otlpreceiver v0.142.0
      # TODO when we push a version of obi receiver, change to that
      # go.opentelemetry.io/obi/collector v0.3.0

providers:
  - gomod: go.opentelemetry.io/collector/confmap/provider/envprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/fileprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/httpsprovider v1.18.0
  - gomod: go.opentelemetry.io/collector/confmap/provider/yamlprovider v1.18.0
